apply plugin: 'com.android.application'

android {
    namespace 'com.game2048'
    compileSdk 34

    defaultConfig {
        applicationId "com.game2048"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    if (project.hasProperty('android.injected.signing.store.file')) {
        signingConfigs {
            release {
                storeFile file(android.injected.signing.store.file)
                storePassword android.injected.signing.store.password
                keyAlias android.injected.signing.key.alias
                keyPassword android.injected.signing.key.password
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
